/* Auto-generated by vfft_v2 — BLOCK-SPLIT interior family, PIPELINE-HOSTED
 * (codelet_zsplit.ml; docs/roadmap/zil_pipeline_port.md). Scratch = 64-B
 * [re x4][im x4] blocks (z addressing +4 for im; one stream per leg row).
 * stfl (ZTURN-S terminator, LOADED twiddle stream: section-tap loads, every power w^1..w^(R-1) a loaded [c x4][s x4] record as a memory operand — no squaring tree, no live twiddle registers — REINT drev-comb stores), fwd.
 * CONTRACT: count % 4 == 0 (4 columns per iteration).
 * tw_re = LOADED per-column stream at tw_re + 6*k: per 4-column group (R-1) records [c(k..k+3)][s(k..k+3)] of w^1..w^3 in leg order. tw_im unused. */
/* ===================== PROVENANCE =====================
 * Generated by: gen_radix.exe 4 --zp-stfl --zp-r0 8 --isa avx2 --uarch raptor_lake_avx2 --emit-c
 * Env overrides: (none)
 * Family: zsplit-pipeline
 * kind=stfl radix=4 dir=fwd isa=avx2 r0=8 (ZTURN-S sectioned geometry)
 * math: Dft.dft_expand_twiddled TP_Flat DIT sign=Fwd
 * prepare: Pipeline.prepare_codelet (monolithic, fuse=0)
 * schedule: Schedule.su_schedule (SR list scheduler)
 * ====================================================== */
#include <immintrin.h>
#include <stddef.h>

__attribute__((target("avx2,fma")))
void radix4_z_stfl_r8_fwd_avx2(
    const double * __restrict__ zin,
    const double * __restrict__ zin_unused,
    double       * __restrict__ zout,
    double       * __restrict__ zout_unused,
    const double * tw_re, const double * tw_im,
    size_t Ls, size_t Gs, size_t OLs, size_t OGs, size_t count)
{
    (void)zin_unused; (void)zout_unused; (void)tw_im; (void)Ls; (void)Gs; (void)OGs;
    for (size_t k = 0; k + 4 <= count; k += 4) {
        /* ZTURN-S section-tap load edge (1 record/section, 64 B, no shuffles) */
        const __m256d lane_re_0 = _mm256_loadu_pd(&zin[2*(size_t)k + 0]);
        const __m256d lane_im_0 = _mm256_loadu_pd(&zin[2*(size_t)k + 4]);
        const __m256d lane_re_1 = _mm256_loadu_pd(&zin[2*((size_t)2*OLs/2 + k) + 0]);
        const __m256d lane_im_1 = _mm256_loadu_pd(&zin[2*((size_t)2*OLs/2 + k) + 4]);
        const __m256d lane_re_2 = _mm256_loadu_pd(&zin[2*((size_t)1*OLs/2 + k) + 0]);
        const __m256d lane_im_2 = _mm256_loadu_pd(&zin[2*((size_t)1*OLs/2 + k) + 4]);
        const __m256d lane_re_3 = _mm256_loadu_pd(&zin[2*((size_t)3*OLs/2 + k) + 0]);
        const __m256d lane_im_3 = _mm256_loadu_pd(&zin[2*((size_t)3*OLs/2 + k) + 4]);
        /* SU-scheduled body (pipeline) */
        const __m256d t0 = lane_re_3;
        const __m256d t1 = _mm256_loadu_pd(&tw_re[6*(size_t)k + 16]);
        const __m256d t2 = lane_im_3;
        const __m256d t3 = _mm256_loadu_pd(&tw_re[6*(size_t)k + 20]);
        const __m256d t4 = _mm256_fnmadd_pd(t2, t3, _mm256_mul_pd(t0, t1));
        const __m256d t5 = _mm256_fmadd_pd(t0, t3, _mm256_mul_pd(t2, t1));
        const __m256d t9 = lane_re_1;
        const __m256d t10 = _mm256_loadu_pd(&tw_re[6*(size_t)k + 0]);
        const __m256d t11 = lane_im_1;
        const __m256d t12 = _mm256_loadu_pd(&tw_re[6*(size_t)k + 4]);
        const __m256d t13 = _mm256_fnmadd_pd(t11, t12, _mm256_mul_pd(t9, t10));
        const __m256d t14 = _mm256_fmadd_pd(t9, t12, _mm256_mul_pd(t11, t10));
        const __m256d t16 = _mm256_sub_pd(t14, t5);
        const __m256d t18 = _mm256_sub_pd(t13, t4);
        const __m256d t35 = _mm256_add_pd(t5, t14);
        const __m256d t36 = _mm256_add_pd(t4, t13);
        const __m256d t21 = lane_re_2;
        const __m256d t22 = _mm256_loadu_pd(&tw_re[6*(size_t)k + 8]);
        const __m256d t23 = lane_im_2;
        const __m256d t24 = _mm256_loadu_pd(&tw_re[6*(size_t)k + 12]);
        const __m256d t25 = _mm256_fnmadd_pd(t23, t24, _mm256_mul_pd(t21, t22));
        const __m256d t26 = _mm256_fmadd_pd(t21, t24, _mm256_mul_pd(t23, t22));
        const __m256d t28 = lane_re_0;
        const __m256d t32 = _mm256_sub_pd(t28, t25);
        const __m256d t33 = _mm256_sub_pd(t32, t16);
        const __m256d t43 = _mm256_add_pd(t16, t32);
        const __m256d t39 = _mm256_add_pd(t25, t28);
        const __m256d t40 = _mm256_sub_pd(t39, t36);
        const __m256d t45 = _mm256_add_pd(t36, t39);
        const __m256d t29 = lane_im_0;
        const __m256d t30 = _mm256_sub_pd(t29, t26);
        const __m256d t34 = _mm256_add_pd(t18, t30);
        const __m256d t44 = _mm256_sub_pd(t30, t18);
        const __m256d t38 = _mm256_add_pd(t26, t29);
        const __m256d t42 = _mm256_sub_pd(t38, t35);
        const __m256d t46 = _mm256_add_pd(t35, t38);
        /* Z store edge (REINT) */
        const __m256d _pr_0 = _mm256_permute4x64_pd(t45, 0xD8);
        const __m256d _qi_0 = _mm256_permute4x64_pd(t46, 0xD8);
        _mm256_storeu_pd(&zout[2*2*(size_t)k], _mm256_unpacklo_pd(_pr_0, _qi_0));
        _mm256_storeu_pd(&zout[2*2*(size_t)k + 4], _mm256_unpackhi_pd(_pr_0, _qi_0));
        const __m256d _pr_1 = _mm256_permute4x64_pd(t43, 0xD8);
        const __m256d _qi_1 = _mm256_permute4x64_pd(t44, 0xD8);
        _mm256_storeu_pd(&zout[2*((size_t)1*OLs + 2*(size_t)k)], _mm256_unpacklo_pd(_pr_1, _qi_1));
        _mm256_storeu_pd(&zout[2*((size_t)1*OLs + 2*(size_t)k) + 4], _mm256_unpackhi_pd(_pr_1, _qi_1));
        const __m256d _pr_2 = _mm256_permute4x64_pd(t40, 0xD8);
        const __m256d _qi_2 = _mm256_permute4x64_pd(t42, 0xD8);
        _mm256_storeu_pd(&zout[2*((size_t)2*OLs + 2*(size_t)k)], _mm256_unpacklo_pd(_pr_2, _qi_2));
        _mm256_storeu_pd(&zout[2*((size_t)2*OLs + 2*(size_t)k) + 4], _mm256_unpackhi_pd(_pr_2, _qi_2));
        const __m256d _pr_3 = _mm256_permute4x64_pd(t33, 0xD8);
        const __m256d _qi_3 = _mm256_permute4x64_pd(t34, 0xD8);
        _mm256_storeu_pd(&zout[2*((size_t)3*OLs + 2*(size_t)k)], _mm256_unpacklo_pd(_pr_3, _qi_3));
        _mm256_storeu_pd(&zout[2*((size_t)3*OLs + 2*(size_t)k) + 4], _mm256_unpackhi_pd(_pr_3, _qi_3));
    }
}
